### ISSUE TITLE
Why "Async" suffix?

### ISSUE THREAD

**Issue by ibc** [IPWright83/eslint-plugin-async-protect#1]
> This rule enforces that async functions have an Async suffix to their name

So basically all rules added by this plugin depend on `async` functions having "Async" suffix to their name. May I ask *why*? Where is written that `async` functions must be named that way?

**Comment by IPWright83** [comment]
@ibc of course you can ask :)

So there are no guidelines that state you should have a consistent naming pattern for `async` functions. I've found that if you're not using TypeScript then within a codebase it can be difficult to tell whether a function is `async` or not. Having a consistent naming convention helps with that as essentially it auto documents. I searched for something to do this for me, and there was one suggestion labelled as being too opinionated for core but fit for a plugin (so I created one!). https://github.com/eslint/eslint/issues/8531

When combined with the `async-protect/async-await` rule, you can protect against missing `await` keywords. The benefit is because you've now got a consistent naming convention in your codebase - this check can be carried out across files, whereas other plugins can only work where the function is both declared and called in the same file.

It is an opinionated rule - and by all means if you don't like it feel free not to use it. I originally came up with the idea after spending way too long trying to identify why tests were failing using a test runner (WallabyJS) which doesn't have great debugging support. It turned out some existing code was missing an `await` and it wasn't obvious the function needed awaiting... I realised I could solve that via consistent naming.

**Comment by ibc** [comment]
Thanks. It makes sense. I do not like much that naming convention, but it's legit :)

Let me close the issue.
